version: '3'
services:

  mysql:
    image: ghcr.io/getimages/mysql:8.0.25
    container_name: sample_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-app}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: ghcr.io/getimages/redis:6.2.4-buster
    container_name: sample_redis
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./docker/redis:/data
    ports:
      - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
